### ISSUE TITLE
[BUG] Migrate from request to fetch() - Connections left open

### ISSUE THREAD

**Issue by Axcelers** [noblox/noblox.js#788] opened 2024-03-26 15:08 UTC
I suggest we should migrate to fetch(). The API connections keeps getting left open, making noblox.js an unreliable source. My bots have been unreliable due to noblox.js using requests.

For example, once the bots start, the API will work without issue. However, due to recent issues with the request package since its been deperacated, connections have been being left open causing some noblox.js functions to not complete from time to time. For example, NBX.promote() or NBX.setRank().

This is an URGENT issue that needs to be resolved as there isn't really any other reliable package for my case.

**Comment by Neztore** [comment] 2024-03-26 15:10
Duplicate of #143  - Pull requests welcome.

**Closed by Neztore** 2024-03-26 15:10 UTC
