### ISSUE TITLE
[BUG] Outdated API for checkDeveloperProductName.js

### ISSUE THREAD

**Issue by emsar69** [noblox/noblox.js#783] opened 2024-03-16 11:21 UTC
**Describe the bug**
checkDeveloperProductName.js keep saying user not logged in.

**To Reproduce**
I fixed bug by changing module's source code and updated API

Changes I've made:
[checkDeveloperProductName.txt](https://github.com/noblox/noblox.js/files/14623354/checkDeveloperProductName.txt)
[addDeveloperProduct.txt](https://github.com/noblox/noblox.js/files/14623355/addDeveloperProduct.txt)

I appreciate to help you:)

**Comment by Neztore** [comment] 2024-04-06 11:39
#785

**Comment by Neztore** [comment] 2024-04-06 11:41
Duplicate of #748

**Closed by Neztore** 2024-04-06 11:41 UTC
Labels: bug
