### ISSUE TITLE
Problem with onJoinRequestHandle

### ISSUE THREAD

**Issue by TheInspector556** [noblox/noblox.js#501] opened 2022-01-10 16:32 UTC
After the bot accepts someone the first time it starts up lets say someone requested it will accept if then someone else procceds to request after the first one the it won't detect the other one.
![image](https://user-images.githubusercontent.com/76826756/148802275-e7a5bfd5-1d69-405e-afc6-cf246c48e500.png)
^ that is an imagine of someone getting accepted lol

also this is how i made the event
![image](https://user-images.githubusercontent.com/76826756/148802778-ed57bf59-f805-41c8-b45c-5778edc0adfa.png)

**Comment by Aerosphia** [comment] 2022-01-11 01:52
yeah, this is a shortPoll issue to my understanding. i already reported it @ #488

**Comment by Neztore** [comment] 2022-01-11 23:50
Duplicate of #488

**Closed by Neztore** 2022-01-11 23:50 UTC
