### ISSUE TITLE
[BUG] cant use Add Developer Product

### ISSUE THREAD

**Issue by Xoltage** [noblox/noblox.js#776] opened 2024-01-22 03:56 UTC
![image](https://github.com/noblox/noblox.js/assets/105898004/13461559-5166-4661-944e-7155fe96b5c6)

**Comment by HolyItsTio** [comment] 2024-01-27 21:07
Heyya! Go into your node_modules/noblox.js/lib/games/addDeveloperProduct.js and just remove the checkDeveloperProduct function from there, it really doesn't need to exist and you can basically handle the error when the product already exists yourself. Np!

**Comment by Neztore** [comment] 2024-04-06 11:41
Duplicate of #748

**Closed by Neztore** 2024-04-06 11:41 UTC
